apiVersion: batch/v1
kind: CronJob
metadata:
  name: threatgen
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: threatgen
        spec:
          containers:
          - name: threatgen
            image: dockerbadboy/art:latest
            command: ["pwsh", "-c", "(./RunTests.ps1 CONNECT.UNEXPECTED SUBTERFUGE.CURL.SOCKS)"]
            securityContext:
              privileged: true
          nodeSelector:
            kubernetes.io/os: linux
          restartPolicy: OnFailure
